---
title: "Learning Resources"
output:
  html_document:
    toc: true
    toc_float: true
---

<br>

## R

* **["Learn R 4 Free (resources in English, Spanish, Turkish)"](https://www.learnr4free.com/index.html)**
  * Page with links to free resources for learning R.
* **["SICSS Bootcamp"](https://sicss.io/boot_camp)**
  * Bootcamp for R
* **["R for Data Science"](https://r4ds.had.co.nz/)**
  * A resource for beginners who are interested in learning both the basics of R and data science.
* **["Advanced R"](http://adv-r.had.co.nz/Introduction.html)**
  * A resource for more advanced R users who are interested in learning more in-depth knowledge about how the R programming language works.
* **["The tidyverse style guide"](https://style.tidyverse.org/)**
  * A style guide for writing R code (requires a VPN to access in mainland China)
* **["Tidyverse"](https://www.tidyverse.org/)**
  * Website with resources for using the tidyverse, one of the most popular collections of R packages 
* **["R Packages"](http://r-pkgs.had.co.nz/)**
  * A guide to building a R package
* **["Ten Steps to Becoming a Tidyverse Contributor"](https://thisisnic.github.io/2018/11/28/ten-steps-to-becoming-a-tidyverse-contributor/)**
  * A guide to contributing to R open source packages
* **["Creating websites in R"](https://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html#types_of_websites)**
  * A quick guide to making a website using RMarkdown

<br><br>

## Python

* **["Dartmouth College CS 1 Curriculum"](https://www.cs.dartmouth.edu/~cs1/)**
  * Website for Dartmouth College's Computer Science 1 course

<br><br>

## SQL

* **["SQL Murder Mystery"](http://mystery.knightlab.com/)**
  * An interactive website for learning SQL

<br><br>

## Git and GitHub

* **["Resources to learn Git"](https://try.github.io/)**
  * Resources compiled by GitHub for learning Git
* **["GitHub Learning Lab"](https://lab.github.com/)**
  * Interactive tool from GitHub for learning Git

<br><br>

## Machine Learning/Data Science

* **["The Elements of Statistical Learning"](https://web.stanford.edu/~hastie/ElemStatLearn/)**
  * A free online textbook for statistical learning
* **["Data Science for Economists"](https://raw.githack.com/uo-ec607/lectures/master/08-regression/08-regression.html)**
  * Data science for economists lecture with links to resources
* **["Data Science in a Box"](https://datasciencebox.org/)**
  * Intro data science course
  
## Statistics

* **["Open Intro Stats"](https://github.com/OpenIntroStat/ims)**
  * Free online resources for intro statistics
* **["Intro to Stats in R"](https://stat150.blog/)**
  * Introductory statistics using R
* **["Resampling Methods in R"](https://erbiostat.wixsite.com/bootstrap)**
  * Bootstrapping and other methods in R
  
